# Generated by Django 4.1.3 on 2023-11-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultmanagementapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.IntegerField()),
                ('name', models.CharField(default='a', max_length=45)),
                ('std_id', models.IntegerField()),
                ('c_id', models.IntegerField()),
                ('marks', models.IntegerField()),
            ],
            options={
                'unique_together': {('std_id', 'exam_id')},
            },
        ),
    ]
